### PR TITLE
plat-smt submission

### PR DESCRIPTION
**Pull request by dewert99**

### CODE REVIEW

**Comment by mbromber** [comment]
We are really sorry, but we made an error in the last iteration of the rules. The requirement that the submission is a Dockerfile was an idea that we forgot to remove. The submitted file must be an archive that contains the executable precompiled (statically linked is preferable). It will be executed on a computer that has the same installation as the docker image: registry.gitlab.com/sosy-lab/benchmarking/competition-scripts/user:latest
For more details on the image see https://gitlab.com/sosy-lab/benchmarking/competition-scripts/
#computing-environment-on-competition-machines.

PS: Not sure if you are on one of the following mailing lists. If not, we recommend you to join at least the smt-announce group. We sometimes post updates on the competition there including the above information.

smt-comp@cs.nyu.edu
smt-lib@googlegroups.com
smt-announce@googlegroups.com

**Comment by dewert99** [comment]
> I added the extension .json to the file

@bobot, Thanks for fixing this. It seems like your commit [29b94be](https://github.com/SMT-COMP/smt-comp.github.io/pull/55/commits/29b94bebada9361649649b7106e56d0998d95e09) also changed some other files which are now causing CI to fail. Do you know what I should do about this?

**Comment by dewert99** [comment]
> Just to know, if the command is the same everywhere you don't have to add it in each participation (inherited from the root)

Thanks, I fixed this

**Comment by martinjonas** [comment]
@dewert99 We have executed the latest version of plat-smt on a randomly chosen subset of 20 single-query benchmarks from each logic where it participates. The benchmarks are also scrambled by the competition scrambler (with seed 1). You can find the results here: https://www.fi.muni.cz/~xjonas/smtcomp/platsmt.table.html#/table

Quick explanation:
- Green `status` means that the result agrees with the `(set-info :status _)` annotation from the benchmark.
- Blue `status` means that the benchmark has annotation `(set-info :status unknown)`.
- By clicking on the result (e.g. `false`, `true`, `ABORTED`, …) you can see the command-line arguments with which your solver was called and its output on the benchmark.
- By clicking on the benchmark name (i.e., `*scrambled*.yml`), you can see the details of the benchmark including its contents (by clicking on the file link in `input_files`) and the name of the original bennchmark before scrambling (e.g., `# original_files: 'non-incremental/AUFBVFP/20210301-Alive2-partial-undef/ph7/583_ph7.smt2'`).

Please check whether there are some discrepancies, such as missing/extra logics, unexpected aborts or `unknown`s, and similar. If you update the solver, let me know and I can execute further test runs. We still have plenty of time for several follow-up test runs.

**Comment by martinjonas** [comment]
@dewert99 We have finished test runs of model-validation and unsat-core generation tracks. You can find the results here:
- https://www.fi.muni.cz/~xjonas/smtcomp/platsmt_model.table.html#/table
- https://www.fi.muni.cz/~xjonas/smtcomp/platsmt_unsatcore.table.html#/table

As before, you can click on the status of the benchmark to see the output of your solver. If you find any discrepancies or extra/missing logics, please let me know.

Note that we selected only SAT benchmarks for model validation and only UNSAT for unsat-core generation. As a result of that, some logics do not contain any benchmarks. So do not be surprised if you have subscribed to one of these logics and you do not have any result for it. In particular, the logics are:

For model-generation: QF_UFFP, QF_UFBVDT, QF_UFDTNIA, QF_NIRA.

For unsat-core: UFBVDT, FPLRA, QF_AUFBVFP, QF_ABVFPLRA, QF_UFBVDT, QF_UFDTNIA, QF_UFDT, QF_NIA, QF_SNIA.

**Comment by martinjonas** [comment]
@dewert99 Have you tried the incremental version of `plat-smt` using the official trace executor that is used in the competition (https://github.com/SMT-COMP/trace-executor)? If I run `plat-smt` using the trace executor, it times out on all of the benchmarks. My example usage is:
```
> ./smtlib2_trace_executor unpack/5c90e10410713e76b57084fe0a5f22051d6b1be606608d1f7185cbdb55e84ae9/plat-smt -i benchmarks/files_inc/QF_UF/scrambled11414.smt2
```
The benchmark is here: 
[scrambled11414.smt2.tar.gz](https://github.com/user-attachments/files/15818201/scrambled11414.smt2.tar.gz)

Please check that the solver indeed supports the interactive usage of the incremental solver. I.e., that it reads the commands from the standard input and processes the commands as they come (and is not waiting until the end of the input). Thanks!

**Comment by dewert99** [comment]
@martinjonas Thanks for catching my mistake, I uploaded a new version that should fix the issue.

**Pull request merged**
