### PR TITLE
submission iProver

### PR DESCRIPTION
**Pull request by konstantin-korovin**

### CODE REVIEW

**Comment by martinjonas** [comment]
@konstantin-korovin Just fyi: the archive is still missing in the submission. If you are still planning to update it, feel free to ignore this notification. We just wanted to be on the safe side. (And the sooner you provide us with an archive, the sooner we can execute the preliminary experiments and give you feedback and more time to fix potential bugs.)

**Comment by konstantin-korovin** [comment]
Hi Martin,

Thanks for the notification, I'll upload a version soon and let you know.

Regards,
Konstantin

**Comment by martinjonas** [comment]
@konstantin-korovin Just to be sure: this pull request is outdated and was superseded by #96, correct?

**Comment by konstantin-korovin** [comment]
Yes, with the last commit 4ba6676
<https://github.com/SMT-COMP/smt-comp.github.io/pull/96/commits/4ba6676a67d644895e54fca0e5afa632acacc361>
"final"


Thanks,
Konstantin

**Pull request closed without merging**
