### PR TITLE
Solver submission: cvc5

### PR DESCRIPTION
**Pull request by hansjoergschurr**
Thank you for running the competition.

### CODE REVIEW

**Comment by martinjonas** [comment]
@hansjoergschurr We have executed the latest version of cvc5 on a randomly chosen subset of 20 single-query benchmarks from each logic where it participates. The benchmarks are also scrambled by the competition scrambler (with seed 1). You can find the results here: https://www.fi.muni.cz/~xjonas/smtcomp/cvc5.table.html#/table

Quick explanation:
- Green `status` means that the result agrees with the `(set-info :status _)` annotation from the benchmark.
- Blue `status` means that the benchmark has annotation `(set-info :status unknown)`.
- By clicking on the result (e.g. `false`, `true`, `ABORTED`, …) you can see the command-line arguments with which your solver was called and its output on the benchmark.
- By clicking on the benchmark name (i.e., `*scrambled*.yml`), you can see the details of the benchmark including its contents (by clicking on the file link in `input_files`) and the name of the original bennchmark before scrambling (e.g., `# original_files: 'non-incremental/AUFBVFP/20210301-Alive2-partial-undef/ph7/583_ph7.smt2'`).

Please check whether there are some discrepancies, such as missing/extra logics, unexpected aborts or `unknown`s, and similar. If you update the solver, let me know and I can execute further test runs. We still have plenty of time for several follow-up test runs.

**Comment by martinjonas** [comment]
@hansjoergschurr Here are also results of the test run on a small subset of **incremental** benchmarks: https://www.fi.muni.cz/~xjonas/smtcomp/cvc5_inc.table.html#/table

The status column has the following meaning:
- `DONE (X correct)`: the solver terminated successfully and correctly decided X `(check-sat)` queries before that.
- `SOMETHING_ELSE (X correct)` (e.g., `TIMEOUT (10 correct)` or `ABORTED (10 correct)`): The solver did not terminate successfully, but correctly decided X `(check-sat)` queries before it crashed or was killed.
- `WRONG`: There was at least one answer to `(check-sat)` that did not agree with the status specified in the benchmark.

Again, if there are discrepancies (missing/extra logics, unexpected results), please let me know.

**Comment by martinjonas** [comment]
@hansjoergschurr We have finished test runs of model-validation and unsat-core generation tracks. You can find the results here:
- https://www.fi.muni.cz/~xjonas/smtcomp/cvc5_model.table.html#/table
- https://www.fi.muni.cz/~xjonas/smtcomp/cvc5_unsatcore.table.html#/table

As before, you can click on the status of the benchmark to see the output of your solver. If you find any discrepancies or extra/missing logics, please let me know.

Note that we selected only SAT benchmarks for model validation and only UNSAT for unsat-core generation. As a result of that, some logics do not contain any benchmarks. So do not be surprised if you have subscribed to one of these logics and you do not have any result for it. In particular, the logics are:

For model-generation: QF_UFFP, QF_UFBVDT, QF_UFDTNIA, QF_NIRA.

For unsat-core: UFBVDT, FPLRA, QF_AUFBVFP, QF_ABVFPLRA, QF_UFBVDT, QF_UFDTNIA, QF_UFDT, QF_NIA, QF_SNIA.

**Comment by Gbury** [comment]
After a bit of reading, it's not clear whether this is compliant with the standard (but it's not clear that it is not compliant either), mainly because the standard for models is quite imprecise. The most relevant quote I could find was:

> [In]: (define-fun f ((x1 σ1) · · · (xn σn)) σ t)
> The term t is expected, although not required, to be a value when f is a constant (i.e., when n = 0).

In such cases, i.e. the definition of a non-function value in a model, `dolmen` tries and evaluate the term into a value[1], which in this case fails because no value for `x23` can be found at that point in time.

I'd argue that it's better for solvers to produce models in topological order, because 1) it makes it far easier to check, but also 2) I think it makes more sense: indeed, in the rest of the standard, typechecking of terms follows the regular scoping rules, and in particular terms cannot refer to constants declared later and 3) it is a good guard against accidental infinite recursive values (such as an infinite list) which I'm not sure we want to allow (and would probably make `dolmen` loop infinitely in the current state). If we ever decide to allow recursive/infinite values, then from the implementation perspective, it would be reasonable to allow out-of-order definitions though.

[1]: Note that this is the case for non-function values; in the case of functions, the body is only evaluated at each call site, so this gives a bit more freedom.

**Comment by Gbury** [comment]
For the part about defining the undefined values of a selector, here is the syntax currently accepte by `dolmen` :
- input file : https://github.com/Gbury/dolmen/blob/master/tests/model/adt/partial_destructor.smt2
- model : https://github.com/Gbury/dolmen/blob/master/tests/model/adt/partial_destructor.rsmt2

As can be seen it is possible to use different definitions for different instances of a polymorphic selector if needed (even if the example only defines one for the `Int` case).

**Pull request merged**
